export {default as MenuItems} from './menuItems'
export {default as Slider} from './slider'
export {default as ContactItem} from './contactItem'
export {default as SideBar} from './sideBar'
export {default as Cart} from './cart'