export {default as Navbar} from './navbar'
export {default as HeroSection} from './hero'
export {default as AboutUs} from './aboutUs'
export {default as Contacts} from './contact'
export {default as Services} from './services'
export {default as MobileNavBar} from './mobileNavBar'
export {default as Footer} from './footer'